environment:
  # For Python versions available on Appveyor, see
  # https://www.appveyor.com/docs/windows-images-software/#python
  matrix:
    - {APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019, PYTHON: "C:\\Python311-x64"}

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python.exe -m pip install codecov coverage pytest-cov numpy<2 scipy"

build: off

test_script:
  - "py.test --cov=. --cov-branch --cov-report=xml -v ."

on_success:
  - "codecov --file coverage.xml"
