name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          python-version: 3.11  # Need to match that used by ChimeraX
          with_qt:
        - os: macos-latest
          python-version: 3.11  # Need to match that used by ChimeraX
          with_qt: true
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install coverage scipy 'numpy<2' pytest-cov flake8 pep8-naming
        if [ "${{ matrix.with_qt }}" = "true" ]; then pip install PyQt5; fi;
    - name: Test
      run: |
        if [ "${{ matrix.with_qt }}" = "true" ]; then export RMF_DISABLE_QT_MOCK=1; fi;
        py.test --cov=. --cov-branch --cov-report=xml -v .
        flake8 --ignore N802,N803,N818,E402,W503 --exclude src/windows,src/linux,src/mac,build .
    - uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
